# Generated by Django 5.1.4 on 2026-04-13 14:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ball',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('over_number', models.PositiveIntegerField()),
                ('ball_number', models.PositiveIntegerField()),
                ('runs_scored', models.PositiveIntegerField(default=0)),
                ('is_wide', models.BooleanField(default=False)),
                ('is_noball', models.BooleanField(default=False)),
                ('is_wicket', models.BooleanField(default=False)),
                ('is_boundary', models.BooleanField(default=False)),
                ('extra_runs', models.PositiveIntegerField(default=0)),
                ('total_runs', models.PositiveIntegerField(default=0)),
                ('wicket_type', models.CharField(blank=True, choices=[('BOWLED', 'Bowled'), ('CAUGHT', 'Caught'), ('RUN_OUT', 'Run Out'), ('STUMPED', 'Stumped'), ('HIT_WICKET', 'Hit Wicket')], max_length=20, null=True)),
                ('is_free_hit', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'balls',
                'ordering': ['over_number', 'ball_number', 'timestamp'],
            },
        ),
    ]
