# Generated by Django 5.1.4 on 2026-04-13 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        ('scoring', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ball',
            name='bowler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balls_as_bowler', to='teams.player'),
        ),
        migrations.AddField(
            model_name='ball',
            name='dismissed_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dismissals', to='teams.player'),
        ),
        migrations.AddField(
            model_name='ball',
            name='fielder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fielding_events', to='teams.player'),
        ),
        migrations.AddField(
            model_name='ball',
            name='innings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balls', to='matches.innings'),
        ),
        migrations.AddField(
            model_name='ball',
            name='non_striker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balls_as_non_striker', to='teams.player'),
        ),
        migrations.AddField(
            model_name='ball',
            name='striker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balls_as_striker', to='teams.player'),
        ),
    ]
