# Generated by Django 5.1.4 on 2026-04-13 14:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pools',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('overs', models.PositiveIntegerField()),
                ('total_teams', models.PositiveIntegerField()),
                ('players_per_team', models.PositiveIntegerField()),
                ('pool_count', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('SETUP', 'Setup'), ('POOL_STAGE', 'Pool Stage'), ('KNOCKOUTS', 'Knockouts'), ('COMPLETED', 'Completed')], default='SETUP', max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tournaments',
                'ordering': ['-created_at'],
            },
        ),
    ]
