# Generated by Django 5.1.4 on 2026-04-14 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_initial'),
        ('tournament', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='mot_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mot_awards', to='teams.player'),
        ),
    ]
