# Generated by Django 5.1.4 on 2026-04-13 14:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Innings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('innings_number', models.PositiveIntegerField()),
                ('total_runs', models.PositiveIntegerField(default=0)),
                ('total_wickets', models.PositiveIntegerField(default=0)),
                ('total_overs', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('extras', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'innings',
                'ordering': ['innings_number'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('POOL', 'Pool'), ('SEMI_FINAL', 'Semi Final'), ('THIRD_PLACE', 'Third Place'), ('FINAL', 'Final')], default='POOL', max_length=20)),
                ('match_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('TOSS', 'Toss'), ('IN_PROGRESS', 'In Progress'), ('INNINGS_BREAK', 'Innings Break'), ('COMPLETED', 'Completed'), ('FORFEITED', 'Forfeited'), ('ABANDONED', 'Abandoned')], default='SCHEDULED', max_length=20)),
                ('toss_decision', models.CharField(blank=True, choices=[('BAT', 'Bat'), ('BOWL', 'Bowl')], max_length=4, null=True)),
                ('result_summary', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'matches',
                'ordering': ['match_number'],
            },
        ),
    ]
