# Generated by Django 5.1.4 on 2026-04-13 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='innings',
            name='batting_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batting_innings', to='teams.team'),
        ),
        migrations.AddField(
            model_name='innings',
            name='bowling_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowling_innings', to='teams.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='mom_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mom_awards', to='teams.player'),
        ),
    ]
