# Generated by Django 5.1.4 on 2026-04-14 20:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_initial'),
        ('teams', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperOver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('round', models.PositiveIntegerField(default=1)),
                ('team1_runs', models.PositiveIntegerField(default=0)),
                ('team2_runs', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='super_overs', to='matches.match')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.team')),
            ],
            options={
                'db_table': 'super_overs',
                'ordering': ['round'],
                'unique_together': {('match', 'round')},
            },
        ),
    ]
